version: '3.8'

networks:
  traefik:
    external: true

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/var/www
    networks:
      - traefik
    ports:
      - 9000

  web:
    image: nginx:stable #-alpine
    restart: always
    tty: true
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www
    networks:
      - traefik
    ports:
      - 80
    labels:
      - 'traefik.http.routers.teto.rule=Host(`teto.uni-fds.com`)'
