@host = http://teto.localhost/api/v1

POST {{host}}/login
content-type: application/json

{
    "name": "Tet",
    # "password": "12345"
}

###

POST {{host}}/MemberInfo
content-type: application/json

{
    "id": 1
}
